services:
  - type: web
    name: korapay-web
    plan: free
    runtime: node
    buildCommand: |
      pnpm install --frozen-lockfile &&
      pnpm --filter @korapay/web build
    startCommand: cd apps/web && pnpm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://korapay-api.fly.dev/api/v1
      - key: NEXT_PUBLIC_SITE_URL
        value: https://korapay-web.onrender.com
      - key: HOSTNAME
        value: 0.0.0.0
      - key: PORT
        value: 10000
